CREATE TABLE AIA_USERS (
  USER_ID INTEGER  NOT NULL ,
  USER_NAME VARCHAR(20) NOT NULL,
  FIRST_NAME VARCHAR(20) NULL,
  LAST_NAME VARCHAR(20) NULL,
  PASS VARCHAR(45) NULL,
  CREATED_DATE DATE NULL,
  CREATED_BY VARCHAR(20) NULL,
  MODIFIED_DATE DATE NULL,
  MODIFIED_BY VARCHAR(20) NULL,
  CONSTRAINT pk_USER_ID PRIMARY KEY (USER_ID)
  );

CREATE TABLE AIA_SETTINGS (
  SETTINGS_ID INTEGER  NOT NULL ,
  USER_ID INTEGER  NOT NULL,
  PLATFORM VARCHAR(25) NOT NULL,
  URL VARCHAR(60) NULL,
  PASSWORD_2 VARCHAR(50) NULL,
  ORGANISATION VARCHAR(50) NULL,
  CREATED_DATE DATE NULL,
  MODIFIED_DATE DATE NULL,
  CREATED_DY VARCHAR(25) NULL,
  MODIFIED_BY VARCHAR(25) NULL,
  STATUS_2 VARCHAR(2) NULL,
  PORT VARCHAR(25) NULL,
  CONSTRAINT pk_SETTINGS_ID PRIMARY KEY (SETTINGS_ID),
  CONSTRAINT fk_USER_ID FOREIGN KEY (USER_ID) REFERENCES AIA_USERS(USER_ID)
);

CREATE TABLE AIA_MARKETING (
  ATTRIBUTE_ID INTEGER  NOT NULL,
  FILE_ID INTEGER  NOT NULL ,
  MEMBER_FIRST_NAMES VARCHAR(25) NULL,
  MEMBER_SURNAME VARCHAR(25) NULL,
  EMAIL_ADDRESS VARCHAR(25) NULL,
  AIA_VITALITY_MEMBER_NUMBER VARCHAR(25) NULL,
  ENTITY_REFERENCE_NUMBER VARCHAR(25) NULL,
  LANGUAGE_PREFERENCE VARCHAR(25) NULL,
  RECORD_STATUS VARCHAR(2) NULL,
  PROCESS_DATE DATE NULL,
  RECORD_ID INTEGER  NULL,
  CONSTRAINT pk_ATTRIBUTE_ID PRIMARY KEY(ATTRIBUTE_ID)
);

CREATE TABLE AIA_MARKETING_TRAN (
  MARKETING_TRAN_ID INTEGER  NOT NULL ,
  ATTRIBUTE_ID INTEGER  NOT NULL,
  ATTRIBUTE_NAME VARCHAR(25) NULL,
  ATTRIBUTE_VALUE VARCHAR(25) NULL,
  CONSTRAINT pk_MARKETING_TRAN_ID PRIMARY KEY(MARKETING_TRAN_ID),
  CONSTRAINT fk_ATTRIBUTE_ID FOREIGN KEY (ATTRIBUTE_ID) REFERENCES AIA_MARKETING(ATTRIBUTE_ID)
);

CREATE TABLE AIA_MARKETING_HIST (
  ATTRIBUTE_ID INTEGER  NOT NULL ,
  FILE_ID VARCHAR(25) NULL,
  MEMBER_FIRST_NAMES VARCHAR(25) NULL,
  MEMBER_SURNAME VARCHAR(25) NULL,
  MAIL_ADDRESS VARCHAR(25) NULL,
  AIA_VITALITY_MEMBER_NUMBER VARCHAR(25) NULL,
  ENTITY_REFERENCE_NUMBER VARCHAR(25) NULL,
  LANGUAGE_PREFERENCE VARCHAR(2) NULL,
  RECORD_STATUS VARCHAR(2) NULL,
  PROCESS_DATE DATE NULL,
  RECORD_ID INTEGER  NULL,
  CONSTRAINT pk_ATTRIBUTE_HIST_ID PRIMARY KEY(ATTRIBUTE_ID)
);

CREATE TABLE AIA_MARKETING_TRAN_HIST (
  MARKETING_TRAN_ID INTEGER  NOT NULL ,
  ATTRIBUTE_ID INTEGER  NOT NULL,
  ATTRIBUTE_NAME VARCHAR(25) NULL,
  ATTRIBUTE_VALUE VARCHAR(25) NULL,
  CONSTRAINT pk_MARKETING_TRAN_HIST_ID PRIMARY KEY(MARKETING_TRAN_ID),
  CONSTRAINT fk_ATTRIBUTE_HIST_ID FOREIGN KEY (ATTRIBUTE_ID) REFERENCES AIA_MARKETING_HIST(ATTRIBUTE_ID)
);
GO






