package com.aia.model;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AiaMarketing generated by hbm2java
 */
public class AiaMarketing implements java.io.Serializable {

	private int attributeId;
	private int fileId;
	private String memberFirstNames;
	private String memberSurname;
	private String emailAddress;
	private String aiaVitalityMemberNumber;
	private String entityReferenceNumber;
	private String languagePreference;
	private String recordStatus;
	private Date processDate;
	private Integer recordId;
	private Set<AiaMarketingTran> aiaMarketingTrans = new HashSet<AiaMarketingTran>(
			0);

	public AiaMarketing() {
	}

	public AiaMarketing(int attributeId, int fileId) {
		this.attributeId = attributeId;
		this.fileId = fileId;
	}

	public AiaMarketing(int attributeId, int fileId, String memberFirstNames,
			String memberSurname, String emailAddress,
			String aiaVitalityMemberNumber, String entityReferenceNumber,
			String languagePreference, String recordStatus, Date processDate,
			Integer recordId, Set<AiaMarketingTran> aiaMarketingTrans) {
		this.attributeId = attributeId;
		this.fileId = fileId;
		this.memberFirstNames = memberFirstNames;
		this.memberSurname = memberSurname;
		this.emailAddress = emailAddress;
		this.aiaVitalityMemberNumber = aiaVitalityMemberNumber;
		this.entityReferenceNumber = entityReferenceNumber;
		this.languagePreference = languagePreference;
		this.recordStatus = recordStatus;
		this.processDate = processDate;
		this.recordId = recordId;
		this.aiaMarketingTrans = aiaMarketingTrans;
	}

	public int getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(int attributeId) {
		this.attributeId = attributeId;
	}

	public int getFileId() {
		return this.fileId;
	}

	public void setFileId(int fileId) {
		this.fileId = fileId;
	}

	public String getMemberFirstNames() {
		return this.memberFirstNames;
	}

	public void setMemberFirstNames(String memberFirstNames) {
		this.memberFirstNames = memberFirstNames;
	}

	public String getMemberSurname() {
		return this.memberSurname;
	}

	public void setMemberSurname(String memberSurname) {
		this.memberSurname = memberSurname;
	}

	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	public String getAiaVitalityMemberNumber() {
		return this.aiaVitalityMemberNumber;
	}

	public void setAiaVitalityMemberNumber(String aiaVitalityMemberNumber) {
		this.aiaVitalityMemberNumber = aiaVitalityMemberNumber;
	}

	public String getEntityReferenceNumber() {
		return this.entityReferenceNumber;
	}

	public void setEntityReferenceNumber(String entityReferenceNumber) {
		this.entityReferenceNumber = entityReferenceNumber;
	}

	public String getLanguagePreference() {
		return this.languagePreference;
	}

	public void setLanguagePreference(String languagePreference) {
		this.languagePreference = languagePreference;
	}

	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	public Integer getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	public Set<AiaMarketingTran> getAiaMarketingTrans() {
		return this.aiaMarketingTrans;
	}

	public void setAiaMarketingTrans(Set<AiaMarketingTran> aiaMarketingTrans) {
		this.aiaMarketingTrans = aiaMarketingTrans;
	}

}
