package com.aia.model;

/**
 * AiaMarketingTranHist generated by hbm2java
 */
public class AiaMarketingTranHist implements java.io.Serializable {

	private int marketingTranId;
	private AiaMarketingHist aiaMarketingHist;
	private String attributeName;
	private String attributeValue;

	public AiaMarketingTranHist() {
	}

	public AiaMarketingTranHist(int marketingTranId,
			AiaMarketingHist aiaMarketingHist) {
		this.marketingTranId = marketingTranId;
		this.aiaMarketingHist = aiaMarketingHist;
	}

	public AiaMarketingTranHist(int marketingTranId,
			AiaMarketingHist aiaMarketingHist, String attributeName,
			String attributeValue) {
		this.marketingTranId = marketingTranId;
		this.aiaMarketingHist = aiaMarketingHist;
		this.attributeName = attributeName;
		this.attributeValue = attributeValue;
	}

	public int getMarketingTranId() {
		return this.marketingTranId;
	}

	public void setMarketingTranId(int marketingTranId) {
		this.marketingTranId = marketingTranId;
	}

	public AiaMarketingHist getAiaMarketingHist() {
		return this.aiaMarketingHist;
	}

	public void setAiaMarketingHist(AiaMarketingHist aiaMarketingHist) {
		this.aiaMarketingHist = aiaMarketingHist;
	}

	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public String getAttributeValue() {
		return this.attributeValue;
	}

	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue;
	}

}
