package com.aia.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AiaMarketingHist generated by hbm2java
 */
public class AiaMarketingHist implements java.io.Serializable {

	private int attributeId;
	private String fileId;
	private String memberFirstNames;
	private String memberSurname;
	private String mailAddress;
	private String aiaVitalityMemberNumber;
	private String entityReferenceNumber;
	private String languagePreference;
	private String recordStatus;
	private Date processDate;
	private Integer recordId;
	private Set<AiaMarketingTranHist> aiaMarketingTranHists = new HashSet<AiaMarketingTranHist>(
			0);

	public AiaMarketingHist() {
	}

	public AiaMarketingHist(int attributeId) {
		this.attributeId = attributeId;
	}

	public AiaMarketingHist(int attributeId, String fileId,
			String memberFirstNames, String memberSurname, String mailAddress,
			String aiaVitalityMemberNumber, String entityReferenceNumber,
			String languagePreference, String recordStatus, Date processDate,
			Integer recordId, Set<AiaMarketingTranHist> aiaMarketingTranHists) {
		this.attributeId = attributeId;
		this.fileId = fileId;
		this.memberFirstNames = memberFirstNames;
		this.memberSurname = memberSurname;
		this.mailAddress = mailAddress;
		this.aiaVitalityMemberNumber = aiaVitalityMemberNumber;
		this.entityReferenceNumber = entityReferenceNumber;
		this.languagePreference = languagePreference;
		this.recordStatus = recordStatus;
		this.processDate = processDate;
		this.recordId = recordId;
		this.aiaMarketingTranHists = aiaMarketingTranHists;
	}

	public int getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(int attributeId) {
		this.attributeId = attributeId;
	}

	public String getFileId() {
		return this.fileId;
	}

	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	public String getMemberFirstNames() {
		return this.memberFirstNames;
	}

	public void setMemberFirstNames(String memberFirstNames) {
		this.memberFirstNames = memberFirstNames;
	}

	public String getMemberSurname() {
		return this.memberSurname;
	}

	public void setMemberSurname(String memberSurname) {
		this.memberSurname = memberSurname;
	}

	public String getMailAddress() {
		return this.mailAddress;
	}

	public void setMailAddress(String mailAddress) {
		this.mailAddress = mailAddress;
	}

	public String getAiaVitalityMemberNumber() {
		return this.aiaVitalityMemberNumber;
	}

	public void setAiaVitalityMemberNumber(String aiaVitalityMemberNumber) {
		this.aiaVitalityMemberNumber = aiaVitalityMemberNumber;
	}

	public String getEntityReferenceNumber() {
		return this.entityReferenceNumber;
	}

	public void setEntityReferenceNumber(String entityReferenceNumber) {
		this.entityReferenceNumber = entityReferenceNumber;
	}

	public String getLanguagePreference() {
		return this.languagePreference;
	}

	public void setLanguagePreference(String languagePreference) {
		this.languagePreference = languagePreference;
	}

	public String getRecordStatus() {
		return this.recordStatus;
	}

	public void setRecordStatus(String recordStatus) {
		this.recordStatus = recordStatus;
	}

	public Date getProcessDate() {
		return this.processDate;
	}

	public void setProcessDate(Date processDate) {
		this.processDate = processDate;
	}

	public Integer getRecordId() {
		return this.recordId;
	}

	public void setRecordId(Integer recordId) {
		this.recordId = recordId;
	}

	public Set<AiaMarketingTranHist> getAiaMarketingTranHists() {
		return this.aiaMarketingTranHists;
	}

	public void setAiaMarketingTranHists(
			Set<AiaMarketingTranHist> aiaMarketingTranHists) {
		this.aiaMarketingTranHists = aiaMarketingTranHists;
	}

}
