package com.aia.model;

/**
 * AiaMarketingTran generated by hbm2java
 */
public class AiaMarketingTran implements java.io.Serializable {

	private int marketingTranId;
	private AiaMarketing aiaMarketing;
	private String attributeName;
	private String attributeValue;

	public AiaMarketingTran() {
	}

	public AiaMarketingTran(int marketingTranId, AiaMarketing aiaMarketing) {
		this.marketingTranId = marketingTranId;
		this.aiaMarketing = aiaMarketing;
	}

	public AiaMarketingTran(int marketingTranId, AiaMarketing aiaMarketing,
			String attributeName, String attributeValue) {
		this.marketingTranId = marketingTranId;
		this.aiaMarketing = aiaMarketing;
		this.attributeName = attributeName;
		this.attributeValue = attributeValue;
	}

	public int getMarketingTranId() {
		return this.marketingTranId;
	}

	public void setMarketingTranId(int marketingTranId) {
		this.marketingTranId = marketingTranId;
	}

	public AiaMarketing getAiaMarketing() {
		return this.aiaMarketing;
	}

	public void setAiaMarketing(AiaMarketing aiaMarketing) {
		this.aiaMarketing = aiaMarketing;
	}

	public String getAttributeName() {
		return this.attributeName;
	}

	public void setAttributeName(String attributeName) {
		this.attributeName = attributeName;
	}

	public String getAttributeValue() {
		return this.attributeValue;
	}

	public void setAttributeValue(String attributeValue) {
		this.attributeValue = attributeValue;
	}

}
