package com.aia.model;

import java.util.Date;

/**
 * AiaSettings generated by hbm2java
 */
public class AiaSettings implements java.io.Serializable {

	private int settingsId;
	private AiaUsers aiaUsers;
	private String platform;
	private String url;
	private String password2;
	private String organisation;
	private Date createdDate;
	private Date modifiedDate;
	private String createdDy;
	private String modifiedBy;
	private String status2;
	private String port;

	public AiaSettings() {
	}

	public AiaSettings(int settingsId, AiaUsers aiaUsers, String platform) {
		this.settingsId = settingsId;
		this.aiaUsers = aiaUsers;
		this.platform = platform;
	}

	public AiaSettings(int settingsId, AiaUsers aiaUsers, String platform,
			String url, String password2, String organisation,
			Date createdDate, Date modifiedDate, String createdDy,
			String modifiedBy, String status2, String port) {
		this.settingsId = settingsId;
		this.aiaUsers = aiaUsers;
		this.platform = platform;
		this.url = url;
		this.password2 = password2;
		this.organisation = organisation;
		this.createdDate = createdDate;
		this.modifiedDate = modifiedDate;
		this.createdDy = createdDy;
		this.modifiedBy = modifiedBy;
		this.status2 = status2;
		this.port = port;
	}

	public int getSettingsId() {
		return this.settingsId;
	}

	public void setSettingsId(int settingsId) {
		this.settingsId = settingsId;
	}

	public AiaUsers getAiaUsers() {
		return this.aiaUsers;
	}

	public void setAiaUsers(AiaUsers aiaUsers) {
		this.aiaUsers = aiaUsers;
	}

	public String getPlatform() {
		return this.platform;
	}

	public void setPlatform(String platform) {
		this.platform = platform;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getPassword2() {
		return this.password2;
	}

	public void setPassword2(String password2) {
		this.password2 = password2;
	}

	public String getOrganisation() {
		return this.organisation;
	}

	public void setOrganisation(String organisation) {
		this.organisation = organisation;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getCreatedDy() {
		return this.createdDy;
	}

	public void setCreatedDy(String createdDy) {
		this.createdDy = createdDy;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getStatus2() {
		return this.status2;
	}

	public void setStatus2(String status2) {
		this.status2 = status2;
	}

	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

}
