package com.aia.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AiaUsers generated by hbm2java
 */
public class AiaUsers implements java.io.Serializable {

	private int userId;
	private String userName;
	private String firstName;
	private String lastName;
	private String pass;
	private Date createdDate;
	private String createdBy;
	private Date modifiedDate;
	private String modifiedBy;
	private Set<AiaSettings> aiaSettingses = new HashSet<AiaSettings>(0);

	public AiaUsers() {
	}

	public AiaUsers(int userId, String userName) {
		this.userId = userId;
		this.userName = userName;
	}

	public AiaUsers(int userId, String userName, String firstName,
			String lastName, String pass, Date createdDate, String createdBy,
			Date modifiedDate, String modifiedBy, Set<AiaSettings> aiaSettingses) {
		this.userId = userId;
		this.userName = userName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.pass = pass;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.modifiedDate = modifiedDate;
		this.modifiedBy = modifiedBy;
		this.aiaSettingses = aiaSettingses;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getPass() {
		return this.pass;
	}

	public void setPass(String pass) {
		this.pass = pass;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set<AiaSettings> getAiaSettingses() {
		return this.aiaSettingses;
	}

	public void setAiaSettingses(Set<AiaSettings> aiaSettingses) {
		this.aiaSettingses = aiaSettingses;
	}

}
